- Sources/App/configure.swift
@challfry This PR should add the CORS middleware, allowing other clients to access the server's API.
> Add CORS Middleware

- .github/workflows/publish_docs.yml
Add a github workflow for automatic docs generation
> Doc auto generation

- .github/workflows/publish_docs.yml
> Only run docs publish if we're in the main repo

- Sources/App/Resources/Views/Login/createAccount.html
> fix field alignment on register page

- Sources/App/Migrations/Schema Creation/SearchIndexCreation.swift
Forgot to remove the second `english` parameter. Caused errors on db execution in beta environment.
> Bugfix in migration

- Package.resolved
- Sources/App/Helpers/RedisWrapper.swift
- scripts/docker-compose-instance.yml
* Package updates to deal with excessive log warnings from upstream.
* Fixes https://github.com/jocosocial/swiftarr/issues/115
* Instructs the development instance of Postgres to log all queries for debugging.
> Small Things

- Package.resolved
- Sources/App/Migrations/Schema Creation/PerformanceIndexCreation.swift
- Sources/App/Models/UserNote.swift
- Sources/App/Pivots/KaraokeFavorite.swift
- Sources/App/Resources/Views/User/userProfile.html
- Sources/App/configure.swift
This PR does a few things:
1. Adds a migration to create some indexes on various tables with foreign keys. This will improve performance during joins.
2. Adds unique indexes to karaoke favorites and user notes. These will be created for fresh databases only.
3. swift package update
4. Minor HTML template fixes on the view profile page - was trying to fix a bug with user notes in firefox. These fixes did not resolve it, but they do fix incorrect HTML.
> Performance indexes

- Sources/App/configure.swift
- Sources/App/seeds/Private Swiftarr Config/Docker-Template.env
- Sources/App/seeds/Private Swiftarr Config/Template.env
Fixes https://github.com/jocosocial/swiftarr/issues/118
> Allow configuring of cruise start from env

- LICENSE
- Sources/App/Controllers/Structs/ControllerStructs.swift
- Sources/App/Controllers/UserController.swift
- Sources/App/Resources/Assets/public/codeofconduct.json
- Sources/App/Resources/Views/Login/createAccount.html
- Sources/App/Resources/Views/codeOfConduct.html
- Sources/App/Resources/Views/moderation/guide.html
> Remove 'monkey' references in text, update CoC, update guides

- Sources/App/Migrations/Categories.swift
- Sources/App/configure.swift
It has a new name and description. Migrate it!
> Reame "When and Where" category

- Sources/App/Controllers/AdminController.swift
This just keeps the counts updated when we finish an import.
> Some category bookkeeping wasn't taking place on schedule import.

- Sources/App/Helpers/UserCache.swift
Added Vapor, to add locks to Storage.
UserCache also got some rework to add locks.
> Crash fix.

- .gitignore
- .jazzy.yaml
- Sources/App/Controllers/AdminController.swift
- Sources/App/Controllers/AlertController.swift
- Sources/App/Controllers/AuthController.swift
- Sources/App/Controllers/BoardgameController.swift
- Sources/App/Controllers/ClientController.swift
- Sources/App/Controllers/EventController.swift
- Sources/App/Controllers/FezController.swift
- Sources/App/Controllers/ForumController.swift
- Sources/App/Controllers/KaraokeController.swift
- Sources/App/Controllers/ModerationController.swift
- Sources/App/Controllers/Structs/SocketStructs.swift
- Sources/App/Controllers/TwitarrController.swift
- Sources/App/Controllers/UserController.swift
- Sources/App/Controllers/UsersController.swift
- Sources/App/Enumerations/NotificationType.swift
- docs/Swiftarr/Development.md
- docs/Swiftarr/Documentation.md
- scripts/generatedocs.sh
* Closes https://github.com/jocosocial/swiftarr/issues/186, gets structure to a good enough state.
* Fixes https://github.com/jocosocial/swiftarr/issues/166 by correcting the syntax.
* Adds functionality to the `generatedocs.sh` script to dump the docs into any directory.
> More Docs Cleanup

- Sources/swiftarr/Resources/Views/moderation/profileView.html
- Sources/swiftarr/Resources/Views/moderation/userView.html
Static text in the HTML to help guide the mods on the difference between the User Profile mod page and the User mod page.
> Added Moderator Notes to User Profile and User Mod pages

- .jazzy.yaml
- Sources/swiftarr/Helpers/Settings.swift
- Sources/swiftarr/Resources/Views/time.html
- Sources/swiftarr/configure.swift
- Sources/swiftarr/seeds/Private Swiftarr Config/Docker-Template.env
- Sources/swiftarr/seeds/Private Swiftarr Config/Template.env
- Sources/swiftarr/seeds/schedule.ics
- Sources/swiftarr/seeds/test-schedule.ics
- docs/Swiftarr/Configuration.md
- docs/Swiftarr/Database Migration.md
- docs/Swiftarr/Development.md
- docs/Swiftarr/Linux Installation.md
- docs/Swiftarr/MacOS Installation.md
Update some docs, fix time zone wording
> Documentation Updates

- scripts/run.sh
> Auto migrate now migrates every time

- Sources/swiftarr/Resources/Views/Forums/forumPostsList.html
> Fix image overlay in forum search, add pronoun to byline

- Sources/swiftarr/Controllers/FezController.swift
- Sources/swiftarr/Protocols/APIRouteCollection.swift
- Sources/swiftarr/Resources/Views/Fez/seamailThread.html
- Sources/swiftarr/Resources/Views/trunk.html
* Site UI now shows red underline on Today for moderator/twitarrteam new content (https://github.com/jocosocial/swiftarr/issues/349)
* Prevents generating notifications for new seamail posts by a user to privileged mailboxes
* Improves muting/leaving response for privilege users (https://github.com/jocosocial/swiftarr/issues/318)
> Enhancements to privileged seamails

- Sources/swiftarr/Controllers/FezController.swift
- Sources/swiftarr/Resources/Views/Fez/fezJoined.html
- Sources/swiftarr/Resources/Views/Fez/fezOwned.html
- Sources/swiftarr/Resources/Views/Fez/fezRoot.html
- Sources/swiftarr/Site/SiteChatController.swift
Fixes #326 and #353. The docs claim it's already supported but it wasn't.
> Search all LFG modes

- Sources/swiftarr/Controllers/FezController.swift
Found this when deleting a personalevent
> Recalculate next joined appointment on Fez delete

- Sources/swiftarr/Controllers/ForumController.swift
- Sources/swiftarr/Helpers/RedisWrapper.swift
- Sources/swiftarr/Protocols/APIRouteCollection.swift
> Prevent author from getting notification for alertword that they created

- Sources/swiftarr/Migrations/Categories.swift
- Sources/swiftarr/configure.swift
As discussed with the team and THO in Discord, we do not feel it's worth keeping this entire category around anymore.
> Remove the covid forum category

- Sources/swiftarr/Controllers/FezController.swift
- Sources/swiftarr/Resources/Views/Fez/singleFez.html
- Sources/swiftarr/Site/SiteChatController.swift
Reverts jocosocial/swiftarr#387
> Revert "Prevent photos in private event chat"

- Sources/swiftarr/Site/SitePrivateEventController.swift
This is related to #230. Events cruise days are 1-indexed, but LFG cruise days are 0-indexed.
> Fix LFGs showing up on dayplanner

- Sources/swiftarr/Controllers/Structs/AdminControllerStructs.swift
When compiling with docker stack, I encountered the following errors: https://hastebin.com/share/ogelucibev.bash
Making the Hunt structs Sendable fixes compile: 
```
bruce@2023-Bruce-MBP swiftarr % sh scripts/stack.sh -e development build
Managing stack "swiftarr" in "development" mode.
Arguments for docker-compose are: "build"
Using compose file at ./scripts/docker-compose-stack.yml.
Using env file at ./Sources/swiftarr/seeds/Private Swiftarr Config/development.env
[+] Building 305.3s (30/30) FINISHED                                                                                                                                                               docker:desktop-linux
=> [web internal] load .dockerignore …
```
> Make Hunt structs Sendable to fix compile
