jocosocial/swiftarr

- .dockerignore
- Sources/Run/Private Swiftarr Config/Docker-Template.env
- scripts/Dockerfile.linux-testing
- scripts/Dockerfile.stack
- scripts/development.sh
- scripts/docker-compose-development.yml
- scripts/docker-compose-instance.yml
- scripts/docker-compose-linux-testing.yml
- scripts/docker-compose-stack.yml
- scripts/instance.sh
- scripts/linux-testing.sh
- scripts/run.sh
- scripts/stack.sh
* Switch service dependency images to those that do not run as root.
* Reduce privilege level of Swiftarr runtime to not-root (new user called `swiftarr`).
* Ensure that Redis can be configured with a password if we desire.
* Prevent collision between different Docker run configs (stack, instance, linux-testing, development).
* Remove seeds from image build (in favor of volume mounting).
* Persist redis to a volume.
> Improve Docker Security

- .dockerignore
- .gitignore
- INSTALL.md
- scripts/Dockerfile.stack
Some modifications were required to perform Docker builds in an offline environment. It's a bit shady and I'm not proud but the process is repeatable and documented (via INSTALL.md).
This also removes the seeds from the image.
> Enable Offline Docker Builds

- Sources/App/Site/SiteFileController.swift
- Sources/App/configure.swift
This sets us up to easily serve random static content (such as the KrakenPost list). Any content can be dynamically added to the server in the appropriate directory and immediately be available.
> Enable serving static arbitrary content

- Sources/App/Site/SiteEventsController.swift
When downloading an ICS from the schedule that had spaces or quotes in the title, Chrome gave an error: `ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION`. Per https://stackoverflow.com/questions/39404949/err-response-headers-multiple-content-disposition it sounds like this is a Chrome-specific thing and can be solved by quoting the file name. This exploded with quotes in the event title so we now calculate a sanitized event title to use for file downloads. 
Tested in Chrome and Firefox.
> Fix content header disposition issue with chrome

- Sources/App/Resources/Assets/css/swiftarr.css
This makes it a little more obvious that the "Twit-arr" menu is clickable.
> Pointer cursor for Twit-arr menu

- Sources/App/Resources/Assets/js/swiftarrMessages.js
This fixes #55 where websockets fail to connect over SSL because the protocol was hard-coded to be `ws://` which is not supported over HTTPS (`wss://`).
> Fix websockets over ssl

- Sources/Run/Private Swiftarr Config/Docker-Template.env
- Sources/Run/Private Swiftarr Config/Template.env
IIRC `info` was the default for development. Production defaulted to `notice`.
> Add documentation for LOG_LEVEL config

- .swift-format
This enables the use of Apple's [swift-format](https://github.com/apple/swift-format) utility to ensure something resembling a common code style. Defaults are used with the exception of the options specified in this file. We already talked about some code formatting preferences in private so this shouldn't represent anything too odd.
I assume this thing works nearly out-of-the-box on Mac/Xcode. Linux/VSCode was relatively easy to set up after getting the right version to match my Swift version (currently 5.5.2, not 5.6 yet).
> Add support for Swift-Format

- scripts/run.sh
1) Fixes an issue where I was inappropriately triggering a migration call due to a bad table name. The schema is required (`public.user`) otherwise you get a postgres connection specific temporary table.
2) Signals were not getting passed from container runtime (Docker) to the app process because it was being spawned as a child process. Using `exec` effectively replaces the running PID 1 (`/run.sh`) with the app (`/app/Run`) which allows for signals to be passed correctly. See https://github.com/vapor/vapor/issues/2336#issuecomment-620736247 and https://github.com/vapor/api-template/pull/93#discussion_r413179048 for more information.
The most significant overall improvement is that calling `docker[-compose] restart` on the Swiftarr container now exits cleanly and timely rather than …
> Enhancements to the container run script

- Sources/App/configure.swift
In the docker configuration, the default redis password is `password`. Update the swift configuration's password fallback to match.
> Fix redis default password

- Sources/App/Extensions/Fluent+Extensions.swift
The beta environment's database does not use `english` as its default search configuration. Production probably doesn't, either. So, we need to manually specify it when building the search query.
Hopefully this is the last change needed to get full text search working!
> Use english search configuration when querying

- Sources/App/Helpers/DisabledSectionMiddleware.swift
- Sources/App/Helpers/Settings.swift
- Sources/App/Resources/Assets/js/swiftarr.js
- Sources/App/Resources/Views/featureDisabled.html
- Sources/App/Resources/Views/time.html
- Sources/App/configure.swift
- docs/Swiftarr/API Changelist.md
* Fixes https://github.com/jocosocial/swiftarr/issues/77 by ensuring the "all clients, all features" disable combination actually works. Also render the correct template file.
* Cleanup and unification of cruise date settings. IMO it's desirable to set these in `configure.swift` which still requires a `Setting`. We can still use the convenience function for ensuring we get the correct date as coded. But it took me a few different places to find which one actually set the date and that bothered me.
* Set cruise start date and dayofweek for 2023.
* Remove a bunch of useless code in `configure.swift`.
* Unify the swift runtime hostname parameter to `SWIFTARR_IP` which is what the container expects and what is in the example env files. Apparently I missed that we used two different vars for …
> API Docs, Time View Improvements, Settings

- .github/workflows/prevent_file_changes.yml
This PR adds a workflow which will prevent PRs from modifying `Package.resolved`. When we want to start enforcing this (that is, when the release is locked down for boat), re-enable this workflow and set the Branch protection rules for `master` to "Require status checks to pass before merging" - `prevent_file_changes`
> Add workflow to lock Package.resolved

- .github/workflows/prevent_file_changes.yml
Bugfix. The github action doesn't support `push` events, only `pull_request`. So, remove `push`.
> Fix prevent file changes: only run on pull request

- Sources/App/Controllers/KaraokeController.swift
- Sources/App/Site/SiteKaraokeController.swift
This change allows karaoke users to additionally search by a single letter, or by the character `#`. Doing so will return songs whose artists start with the searched letter or any number, respectively. This should work seamlessly with current search clients, unless they are doing their own input validation to restrict searches to be at least 3 letters long (the previous API rule).
> Karaoke: Allow searching by first letter of artist

- Sources/App/Site/SiteKaraokeController.swift
The pagination URLs for karaoke were not URLEncoding the `#` when searching for `#`. This PR fixes it.
> Fix pagination when searching karaoke for #

- scripts/docker-compose-instance.yml
It can be annoying having to re-seed data between docker down and up. This change will keep the volumes for postgres and redis consistent across runs.
If you want to blow away volumes and reset the data to prep for a clean run, simply use `./scripts/instance.sh down -v` - this will remove all volumes.
> Use named volumes for redis & postgres in instance.sh

- Sources/App/Controllers/ForumController.swift
- Sources/App/Protocols/ContentFilterable.swift
Fixes https://github.com/jocosocial/swiftarr/issues/106
* Correct post count based on complex mention match rather than simple string.
* Fix edge case where mentioning a user at the end of a post without a sentence-ending period would trigger a mention but not be visible in the filtered view.
* Expand commentary for the next person to crawl through the mention filter function.
> Fix Mentioning Edge Cases

- Sources/App/Helpers/Settings.swift
Improves the OOBE for anyone running the app who does not set `SWIFTARR_START_DATE` in the environment file. Setting the env var will automatically set the `cruiseStartDayOfWeek` to the appropriate value based on the `cruiseStartDateComponents`. This behavior is not reflected in the raw settings defaults.
> Make default startdayofweek match the startdate

- Sources/App/Controllers/AlertController.swift
Allow TwitarrTeam members to perform operations on announcements.
Additionally, instead of throwing an error when a user without permissions requests inactive announcements, just silently pretend they only asked for active announcements.
Fixes #149
> Allow TwitarrTeam to modify announcements

- Sources/App/Resources/Views/admin/root.html
Announcements view/edit permission (including daily themes, I hope) will be fixed by #157.
Most dangerous operations are restricted to the admin role. TwitarrTeam doesn't need to care about managing user roles - THO can handle that, like they do for moderator promotions.
Fixes #151
> Audit pages on the admin screen: only allow permitted roles to see links

- Sources/App/Controllers/FezController.swift
- Sources/App/Models/FriendlyFez.swift
- Sources/App/Resources/Assets/js/swiftarr.js
- Sources/App/Resources/Views/Fez/fezCreate.html
- Sources/App/Resources/Views/Fez/fezFilter.html
- Sources/App/Resources/Views/Fez/fezJoined.html
- Sources/App/Resources/Views/Fez/fezOwned.html
- Sources/App/Resources/Views/Fez/fezRoot.html
- Sources/App/Site/SiteFriendlyFezController.swift
- docs/Swiftarr/API Changelist.md
The UI was enforcing a range of 2 to 50 for fez min and max participants. This limitation does not exist in the API, and in the case of meetups or large interest groups, is probably undesired. Creating a fez with 0 max capacity means unlimited membership. The UI already has code to handle this - the 2-50 limitation was just on the input fields.
Additionally, the API's `FriendlyFez` initializer was missing a default value of 0 for `maxCapacity`.
In the API, all three Fez list queries (`joined`, `owned`, `open`) now support the `cruiseday` filter param. This allows us to make the filtering consistent across all tabs in the front-end. Also, there's a new filter type, which enables/disables showing fezzes whose start date is more than an hour in the past. If the new filter is omitted, API …
> Fez Min/Max Fix, Improve Fez Filtering

- Sources/swiftarr/Controllers/AlertController.swift
- Sources/swiftarr/Controllers/UserController.swift
- Sources/swiftarr/Helpers/RedisWrapper.swift
- Sources/swiftarr/Image/Image.swift
* Partially addresses https://github.com/jocosocial/swiftarr/issues/244 so I can at least build. This workaround seems to be used by other Swift projects around the internet to get around the issue until Apple does something with Swift itself. More details on the issue.
* Fixes https://github.com/jocosocial/swiftarr/issues/238
* Starts dealing with https://github.com/jocosocial/swiftarr/issues/246
> Fedora woes and Alertwords

- Sources/swiftarr/Site/SiteAdminController.swift
- Sources/swiftarr/Site/SiteController.swift
I was trying to figure out why Tricordarr wasn't calculating the `cruiseDayIndex` the same way as Swiftarr, and after much swearing I realized that perhaps maybe Swiftarr is wrong. If a cruise starts "tomorrow" (which we define as midnight in the `portTimeZone` it is expected that "today's" `cruiseDayIndex` is `-1` (tomorrow is 0, etc). This was not the case since we were not anchoring the current date in the comparison calculation. A sample program using snippets from the various Swiftarr calculations revealed:
```
---
Start: 2024-03-09 05:00:00 +0000
Prior: Day -64 Hour -10 Minute -14
New: Day -65 Hour 0 Minute 0
---
---
Start: 2024-01-03 05:00:00 +0000
Prior: Day 1 Hour 13 Minute 45
New: Day 1 Hour 0 Minute 0
---
---
Start: 2024-01-04 05:00:00 +0000
Prior: Day 0 Hour 13 Minute 45
New: …
```
> Fix issue with theme day of week calculations

- Sources/swiftarr/Controllers/Structs/ControllerStructs.swift
Because of how Kraken works, I had to add the CategoryID for forums returned in forum search results.
Without major changes to how I used Core Data, I couldn't add Forum objects to Core Data without knowing their Category.
> Added CategoryID to ForumListData

- Sources/swiftarr/Controllers/AdminController.swift
- Sources/swiftarr/Controllers/AlertController.swift
- Sources/swiftarr/Controllers/FezController.swift
- Sources/swiftarr/Controllers/Structs/AdminControllerStructs.swift
- Sources/swiftarr/Controllers/Structs/ControllerStructs.swift
- Sources/swiftarr/Controllers/Structs/SocketStructs.swift
- Sources/swiftarr/Enumerations/EventNotificationSetting.swift
- Sources/swiftarr/Enumerations/NotificationType.swift
- Sources/swiftarr/Helpers/RedisWrapper.swift
- Sources/swiftarr/Helpers/Settings.swift
- Sources/swiftarr/Helpers/WebSocketStorage.swift
- Sources/swiftarr/Jobs/EventJobs.swift
- Sources/swiftarr/Models/Event.swift
- Sources/swiftarr/Protocols/APIRouteCollection.swift
- Sources/swiftarr/Resources/Views/admin/serversettings.html
- Sources/swiftarr/Site/SiteAdminController.swift
- Sources/swiftarr/Site/SiteController.swift
- Sources/swiftarr/Site/SiteEventsController.swift
- Sources/swiftarr/configure.swift
- docs/Swiftarr/API Changelist.md
Like most calendaring applications, Swiftarr now generates NotificationSocket messages for upcoming schedule events. These now occur for Events (official+shadow, anything in the schedule that we import from Sched) that the user has favorited/followed (we use the term inconsistently) and for LFGs the user has joined. I made these separate socket notification types in case down the line we want to have different configurations for each.
The generation of these notifications is a globally defined offset before the event/LFG occurs (such as 10 mins before, 5 minutes before, at start time, etc). This can get a little hard to test for Events since the start time for those is defined before/after a sailing. A configuration option exists to transpose the current time into "day of cruise week". …
> Upcoming Event/LFG Notifications

- Sources/swiftarr/Controllers/PhonecallController.swift
This isn't much different than https://github.com/jocosocial/swiftarr/pull/276, but I've tested it a good bit.
Due to https://github.com/vapor/vapor/issues/3155, the server-mediated path won't return the correct error message when attempting to call someone who hasn't favorited you (although the call does fail correctly and doesn't ring the callee's phone). Works correctly in the direct-call path.
Also, freaked out when I saw 5 "Sending incoming phonecall to callee." messages in a row. Turns out it's because I had 5 devices running logged in as that user. Still, this logging is better.
> Make phonecalls only succeed callee has favorited caller.

- Sources/swiftarr/Controllers/MicroKaraokeController.swift
- Sources/swiftarr/Controllers/Structs/ControllerStructs.swift
- Sources/swiftarr/Resources/Views/moderation/mkSnippetView.html
- Sources/swiftarr/Site/SiteModController.swift
The MK snippet moderation page now displays how many slots are filled in the song and how many offers are outstanding.
Info is similar to: "5/38 slots; 4 filler, 0 offered, 1 uploaded".
Also fixes a couple of places where 'kraken' should be changed to 'MicroKaraoke'.
> MK  snippet mod page now shows sub-totals for various snippet states

- Sources/swiftarr/Controllers/AlertController.swift
- Sources/swiftarr/Helpers/Settings.swift
- Sources/swiftarr/Jobs/EventJobs.swift
This all started with a different problem: Since updating to the 2024 schedule, the `nextFollowedEventID` in `/notification/global` wasn't getting updated when the current event had passed. it gets updated when the alert handler gets re-run or the user performs an event favorite mutation. In digging further there was a math problem that only manifest itself if the `cruiseStartDate()` was in the future (which wasn't true until earlier today). The time interval between now and the future start date was negative, which presented a problem when adding that value to the `cruiseStartDate` to get the pretend date during the week. Yeet some `abs()` at that and problem solved.
This also establishes a common place to get the "comparison date" for events and LFGs. The logic was similar in both LFG …
> Fix issues with cruise start in future

- Sources/swiftarr/Resources/Assets/public/clients/README.md
- Sources/swiftarr/Resources/Assets/public/clients/tricordarr.json
This establishes a pattern for serving client-specific data as JSON from the `/public` file server area. This can be consumed by client apps to read any configuration data specific to them. I want to consume this in Tricordarr to avoid needing to ship certain settings with the builds. Clients are responsible for processing their own data, assuming it even exists at all.
> Add Client Data Pattern

- .jazzy.yaml
- Sources/swiftarr/Controllers/PhotostreamController.swift
- Sources/swiftarr/Site/SitePhotostreamController.swift
We have a convention for mod report API endpoints of `/api/v3/:resource/:id/report`. In the SiteUI those routes become `/:resource/report/:id`. The generalized report handlers in Tricordarr don't work with the `:id` and `report` URL path components reversed in this API. Since this is a brand new controller I think we should be consistent with what we've done in the past.
This also expressly includes the `PhotostreamController` in the list of controllers in https://docs.twitarr.com
> Make photostream report API consistent with other APIs

- Sources/swiftarr/Commands/PruneEventForums.swift
- Sources/swiftarr/Helpers/EventParser.swift
- Sources/swiftarr/configure.swift
This address #146 by introducing a management command that can be used in long-lived instances to clean up old event forums for events that are no longer in the schedule. The intention is that this will clean up some of the 500+ event forums in the beta (and my personal instance). This command will likely never be run on-boat or similar context.
> Command to Delete Old Event Forums

- Sources/swiftarr/Controllers/ForumController.swift
- Sources/swiftarr/Extensions/Fluent+Extensions.swift
- Sources/swiftarr/Extensions/Vapor+Extensions.swift
- Sources/swiftarr/Helpers/CryptoHelper.swift
Add optional parameter `order` to forum queries. Supported values are `ascending, descending`.
Also fixes a crypto import to allow building on linux.
Closes #317 
Sort direction controls are not exposed in the UI, but they do work when the URL is edited:
> Forum sort direction

- Sources/swiftarr/configure.swift
Fixes #330 by moving the test data migrations to the end of the database migration list. Should have no effect on previously seeded databases and makes new databases work.
> Fix Fresh Database Migration Error

- Sources/swiftarr/Controllers/AdminController.swift
- Sources/swiftarr/Resources/Assets/js/swiftarr.js
- Sources/swiftarr/Resources/Views/admin/bulkUser.html
- Sources/swiftarr/Site/SiteAdminController.swift
This makes AdminController's `userfileUploadPostHandler` stream its POST data into a file, and makes the HTML form for the userfile upload POST the file directly, instead of wrapping the file in JSON.
Previously, swiftarr.js would create a `FormData()` for this form's values and upload that from the js. This turned the zip file into a uuencoded JSON string. So, now the `fileupload` class special-cases this and makes the form POST the file contents directly in the request body. Part of the reason to do this was to remove the 8-to-6 increase in payload size, part of it was because Vapor's built in content decoders aren't built to decode while streaming in data.
However, this doesn't fully make the operation use streaming. SiteAdminController's `bulkUserfileUploadPostHandler` bounces the …
> Fixes #329.

- Sources/swiftarr/Controllers/ForumController.swift
- Sources/swiftarr/Controllers/Structs/ControllerStructs.swift
- Sources/swiftarr/Resources/Views/Forums/forumCategories.html
- Sources/swiftarr/Site/SiteForumController.swift
- docs/Swiftarr/API Changelist.md
`CategoryData` now implements `Paginator`. This is an implicit breaking change in that the `numThreads` attribute is now removed in favor of `paginator.total`.
> Fixes #236

- Sources/swiftarr/Controllers/FezController.swift
- Sources/swiftarr/Controllers/Structs/SocketStructs.swift
- Sources/swiftarr/Enumerations/NotificationType.swift
- Sources/swiftarr/Protocols/APIRouteCollection.swift
LFGs and Private Events now generate a Socket Notification for all non-owner participants when the event has been canceled. It will not generate notifications if the owner has un-canceled them (by saving).
Also fixes a bug in `storeNextJoinedAppointment` where next LFG could be something that was canceled.
> Fixes #272

- Sources/swiftarr/Controllers/BoardgameController.swift
- Sources/swiftarr/Site/SiteBoardgameController.swift
- docs/Swiftarr/API Changelist.md
Switches the `/api/v3/boardgames/recommend` (which needs a request body payload) to be `POST` rather than `GET`. I stumbled on this while adding boardgames to Tricordarr. The pattern of a `GET` request with a body is non-standard even though it usually works in client libraries. This is the only usage of this pattern in Swiftarr as far as I've encountered.
> Board game recommend POST rather than GET

- Sources/swiftarr/Controllers/ImageController.swift
- Sources/swiftarr/Controllers/UserController.swift
- Sources/swiftarr/Enumerations/AppFeatures.swift
- Sources/swiftarr/Site/SiteController.swift
- Sources/swiftarr/Site/SiteLoginController.swift
#355. Gives us an off-switch for user registration. This is necessary for the pre-embarkation server since at some point we are going to want to shut down registration and do the user export.
> Make User Registration Disable-able

- .jazzy.yaml
- docs/Swiftarr/Privacy.md
I had an update to Tricordarr get rejected because they didn't like my nonexistent privacy policy and account deletion request procedure. I made a link to this one and it got approved so it seems good enough. ChatGPT wrote most of it for me. I hate legalese.
Oh and other misc doc structure improvements
> Add a privacy policy to make Google happy

- Sources/swiftarr/Controllers/AdminController.swift
The old code did not play nice when going from instance to instance (computer to computer). Didn't like when the target directory didn't exist either. Also moved the image copying logic to a dedicated function.
> Fix image copying issues when going from instance to instance

- Sources/swiftarr/Extensions/Foundation+Extensions.swift
Failable initializers are weird.
> Fixes #360.

- Sources/swiftarr/Controllers/EventController.swift
- Sources/swiftarr/Controllers/ForumController.swift
Fixes #314 
- For event forum categories, do not include the event id on forums where the event has been soft deleted
- When accessing an event, if the event is not found, return not found instead of bad request
> ForumListData should not include IDs for deleted events

- Sources/swiftarr/Controllers/Structs/ControllerStructs.swift
- Sources/swiftarr/Controllers/UserController.swift
- docs/Swiftarr/API Changelist.md
Fixes #374 
Sample whoami responses:
With two roles:
```
{"accessLevel":"admin","roles":["karaokemanager","karaokeambassador"],"userID":"47B0FDB3-8FDF-4FE3-BB51-1BF809D63A32","isLoggedIn":true,"username":"admin"}
```
With no roles:
```
{"roles":[],"isLoggedIn":true,"username":"admin","userID":"47B0FDB3-8FDF-4FE3-BB51-1BF809D63A32","accessLevel":"admin"}
```
> 374: Add user access level and roles to whoami

- Sources/swiftarr/Resources/Views/admin/root.html
Make hunt admin page link visible on admin page even if not logged in as admin, since twitarrteam has access to it.
Fixes #422
> Hunt admin page visibility
